name: Build Examples

on: [push]

jobs:
  build_examples:
    name: Build Examples
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
          env:
            NODE_AUTH_TOKEN: '${{ secrets.WEBMASTER_SECRET }}'
      - name: Run Example Build Script
        run: npm run build:examples